/// TLS 1.3 Client State Machine
///
/// Implements the client-side TLS 1.3 handshake for QUIC.

import Foundation
import QUICTLSCore
import Crypto
import Synchronization
import QUICCore

// MARK: - Client State Machine

/// Client-side TLS 1.3 state machine
public final class ClientStateMachine: Sendable {

    private let state = Mutex<ClientState>(ClientState())

    private struct ClientState: Sendable {
        var handshakeState: ClientHandshakeState = .start
        var context: HandshakeContext = HandshakeContext()
        var configuration: TLSConfiguration = TLSConfiguration()

        /// The Embedded-clean post-ServerHello auth FSM, constructed once ServerHello
        /// has been processed. It owns the running transcript + key schedule by value
        /// and encodes the CertificateVerify / Finished auth invariants. The adapter
        /// parses wire bytes, performs X.509, and converts the FSM's returned secrets
        /// into per-encryption-level `TLSOutput`s.
        var authMachine: QUICClientAuthMachine<QUICFoundationProvider>?
    }

    // MARK: - Initialization

    public init() {}

    // MARK: - Start Handshake

    /// Generate ClientHello and start the handshake
    /// - Parameters:
    ///   - configuration: TLS configuration
    ///   - transportParameters: QUIC transport parameters to send
    ///   - sessionTicket: Optional session ticket for resumption
    ///   - attemptEarlyData: Whether to attempt 0-RTT early data
    /// - Returns: The ClientHello message and any TLS outputs
    public func startHandshake(
        configuration: TLSConfiguration,
        transportParameters: Data,
        sessionTicket: SessionTicketData? = nil,
        attemptEarlyData: Bool = false
    ) throws -> (clientHello: Data, outputs: [TLSOutput]) {
        return try state.withLock { state in
            guard state.handshakeState == .start else {
                throw TLSHandshakeError.unexpectedMessage("Handshake already started")
            }

            state.configuration = configuration
            state.context.localTransportParameters = transportParameters
            state.context.sessionTicket = sessionTicket

            // Generate ephemeral key for key exchange (prefer X25519)
            let keyExchange = try KeyExchange.generate(for: .x25519)
            state.context.keyExchange = keyExchange

            // Generate random
            let random = SecureRandom.bytes(count: TLSConstants.randomLength)
            state.context.clientRandom = random

            // Session ID for TLS 1.3 over QUIC
            // RFC 9001 Section 8.4: "For middlebox compatibility, QUIC implementations
            // SHOULD send a legacy_session_id field in ClientHello that contains a
            // 32-byte value generated by the client."
            // However, quictls (used by ngtcp2) requires an empty session ID for QUIC-TLS.
            // Using empty session ID for broader interoperability.
            let sessionID = Data()
            state.context.sessionID = sessionID

            // Build extensions
            var extensions: [TLSExtension] = []

            // supported_versions (required for TLS 1.3)
            extensions.append(.supportedVersionsClient([TLSConstants.version13]))

            // supported_groups
            extensions.append(.supportedGroupsList([.x25519, .secp256r1]))

            // signature_algorithms - comprehensive list for wide compatibility
            extensions.append(.signatureAlgorithmsList([
                .ecdsa_secp256r1_sha256,
                .ecdsa_secp384r1_sha384,
                .rsa_pss_rsae_sha256,
                .rsa_pss_rsae_sha384,
                .rsa_pss_rsae_sha512,
                .ed25519
            ]))

            // key_share
            extensions.append(.keyShareClient([keyExchange.keyShareEntry()]))

            // ALPN
            if !configuration.alpnProtocols.isEmpty {
                extensions.append(.alpnProtocols(configuration.alpnProtocols))
            }

            // Server name (SNI)
            if let serverName = configuration.serverName {
                extensions.append(.serverName(ServerNameExtension(hostName: serverName)))
            }

            // QUIC transport parameters
            extensions.append(.quicTransportParameters(transportParameters))

            // Build the cipher suites list
            var cipherSuites: [CipherSuite] = [.tls_aes_128_gcm_sha256]

            // PSK-related extensions (if we have a session ticket)
            var pskExtensionsInfo: (offered: OfferedPsks, ticket: SessionTicketData)?

            if let ticket = sessionTicket, ticket.isValid() {
                // If resuming, prefer the original cipher suite
                cipherSuites = [ticket.cipherSuite, .tls_aes_128_gcm_sha256]

                // psk_key_exchange_modes (required when offering PSKs)
                // QUIC requires psk_dhe_ke mode
                extensions.append(.pskKeyExchangeModesList([.psk_dhe_ke]))

                // early_data (if attempting 0-RTT)
                // Sanity check: limit max early data to 16MB to prevent memory issues
                // from maliciously large values
                let maxAllowedEarlyData: UInt32 = 16 * 1024 * 1024  // 16 MB
                let effectiveMaxEarlyData = min(ticket.maxEarlyDataSize, maxAllowedEarlyData)

                if attemptEarlyData && effectiveMaxEarlyData > 0 {
                    extensions.append(.earlyDataClient())
                    state.context.earlyDataState.attemptingEarlyData = true
                    state.context.earlyDataState.maxEarlyDataSize = effectiveMaxEarlyData
                }

                // pre_shared_key must be the last extension
                // Create the PSK identity from the ticket
                let pskIdentity = PskIdentity(ticket: ticket)
                let offeredPsks = OfferedPsks(
                    identities: [pskIdentity],
                    binders: [Data(repeating: 0, count: ticket.cipherSuite.hashLength)] // Placeholder
                )
                pskExtensionsInfo = (offered: offeredPsks, ticket: ticket)

                // Initialize key schedule with PSK
                let psk = SymmetricKey(data: ticket.resumptionPSK)
                state.context.keySchedule = TLSKeySchedule(cipherSuite: ticket.cipherSuite)
                state.context.keySchedule.deriveEarlySecret(psk: psk)

                // Store the PSK cipher suite for 0-RTT key output
                // (will be updated to negotiated suite after ServerHello)
                state.context.cipherSuite = ticket.cipherSuite
            }

            // If offering PSK, we need to compute binders using a two-pass approach
            var clientHelloMessage: Data
            if let pskInfo = pskExtensionsInfo {
                let ticket = pskInfo.ticket
                var offeredPsks = pskInfo.offered

                // First pass: Build ClientHello with placeholder binders
                var extensionsWithPsk = extensions
                extensionsWithPsk.append(.preSharedKeyClient(offeredPsks))

                let placeholderClientHello = ClientHello(
                    random: random,
                    legacySessionID: sessionID,
                    cipherSuites: cipherSuites,
                    extensions: extensionsWithPsk
                )

                // Encode ClientHello to get the transcript up to binders
                let clientHelloWithPlaceholder = placeholderClientHello.encodeAsHandshake()

                // Compute the truncated transcript (excluding binders)
                let bindersSectionSize = offeredPsks.bindersSize
                let truncatedClientHello = clientHelloWithPlaceholder.prefix(clientHelloWithPlaceholder.count - bindersSectionSize)

                // Initialize transcript hash with truncated ClientHello
                var transcriptHashForBinder = TranscriptHash(cipherSuite: ticket.cipherSuite)
                transcriptHashForBinder.update(with: Data(truncatedClientHello))

                // Compute binder
                let binderKey = try state.context.keySchedule.deriveBinderKey(isResumption: true)
                state.context.binderKey = binderKey
                let transcriptHash = transcriptHashForBinder.currentHash()
                let finishedKeyForBinder = state.context.keySchedule.finishedKey(from: binderKey)
                let binder = state.context.keySchedule.finishedVerifyData(
                    forKey: finishedKeyForBinder,
                    transcriptHash: transcriptHash
                )

                // Second pass: Rebuild ClientHello with correct binders
                offeredPsks.binders = [[UInt8](binder)]

                var finalExtensions = extensions
                finalExtensions.append(.preSharedKeyClient(offeredPsks))

                let finalClientHello = ClientHello(
                    random: random,
                    legacySessionID: sessionID,
                    cipherSuites: cipherSuites,
                    extensions: finalExtensions
                )

                clientHelloMessage = finalClientHello.encodeAsHandshake()

                // Derive early traffic secret if attempting 0-RTT
                if state.context.earlyDataState.attemptingEarlyData {
                    var earlyTranscript = TranscriptHash(cipherSuite: ticket.cipherSuite)
                    earlyTranscript.update(with: clientHelloMessage)
                    let earlySecret = try state.context.keySchedule.deriveClientEarlyTrafficSecret(
                        transcriptHash: earlyTranscript.currentHash()
                    )
                    state.context.clientEarlyTrafficSecret = earlySecret
                }
            } else {
                // Standard ClientHello without PSK
                let clientHello = ClientHello(
                    random: random,
                    legacySessionID: sessionID,
                    cipherSuites: cipherSuites,
                    extensions: extensions
                )
                clientHelloMessage = clientHello.encodeAsHandshake()
            }

            // Update transcript
            state.context.transcriptHash.update(with: clientHelloMessage)

            // Transition state
            state.handshakeState = .waitServerHello

            // Prepare outputs
            var outputs: [TLSOutput] = []

            // If attempting early data, provide the early keys (0-RTT)
            if let earlySecret = state.context.clientEarlyTrafficSecret,
               let cipherSuite = state.context.cipherSuite {
                outputs.append(.keysAvailable(KeysAvailableInfo(
                    level: .zeroRTT,
                    clientSecret: earlySecret,
                    serverSecret: earlySecret, // Not used for 0-RTT (client-to-server only)
                    cipherSuite: cipherSuite.toQUICCipherSuite
                )))
            }

            return (clientHelloMessage, outputs)
        }
    }

    // MARK: - Process ServerHello

    /// Process a ServerHello message
    /// - Parameter data: The ServerHello message content (without handshake header)
    /// - Returns: TLS outputs (keys available, etc.)
    public func processServerHello(_ data: Data) throws -> [TLSOutput] {
        return try state.withLock { state in
            // Accept ServerHello in waitServerHello or waitServerHelloRetry states
            guard state.handshakeState == .waitServerHello ||
                  state.handshakeState == .waitServerHelloRetry else {
                throw TLSHandshakeError.unexpectedMessage("Unexpected ServerHello in state \(state.handshakeState)")
            }

            let serverHello = try ServerHello.decode(from: data)

            // Check for HelloRetryRequest
            if serverHello.isHelloRetryRequest {
                return try processHelloRetryRequest(serverHello, data: data, state: &state)
            }

            // Verify supported_versions extension
            guard let supportedVersions = serverHello.supportedVersions,
                  supportedVersions.isTLS13 else {
                throw TLSHandshakeError.unsupportedVersion
            }

            // Validate legacy_session_id_echo (must match what we sent)
            guard serverHello.legacySessionIDEcho == state.context.sessionID else {
                throw TLSHandshakeError.invalidExtension("ServerHello legacy_session_id_echo does not match ClientHello")
            }

            // Validate cipher suite (must be one we offered)
            let offeredCipherSuites: [CipherSuite] = [.tls_aes_128_gcm_sha256, .tls_aes_256_gcm_sha384]
            guard offeredCipherSuites.contains(serverHello.cipherSuite) else {
                throw TLSHandshakeError.noCipherSuiteMatch
            }

            // Check for PSK acceptance
            var pskAccepted = false
            if let pskExtension = serverHello.extensions.first(where: { $0.extensionType == .preSharedKey }) {
                if case .preSharedKey(.serverHello(let selectedPsk)) = pskExtension {
                    // Verify the selected identity is valid (we only offer 1 PSK, so must be 0)
                    guard selectedPsk.selectedIdentity == 0 else {
                        throw TLSHandshakeError.invalidExtension("Invalid PSK selection: \(selectedPsk.selectedIdentity)")
                    }

                    // RFC 8446 Section 4.2.11: The cipher suite MUST match the PSK's cipher suite
                    // state.context.cipherSuite was set to ticket.cipherSuite when we started with PSK
                    if let pskCipherSuite = state.context.cipherSuite,
                       pskCipherSuite != serverHello.cipherSuite {
                        throw TLSHandshakeError.invalidExtension(
                            "Cipher suite mismatch: PSK uses \(pskCipherSuite), server selected \(serverHello.cipherSuite)"
                        )
                    }

                    pskAccepted = true
                    state.context.pskUsed = true
                    state.context.selectedPskIdentity = selectedPsk.selectedIdentity
                }
            }

            // Get key_share extension (required even for PSK-DHE mode)
            guard let serverKeyShare = serverHello.keyShare else {
                throw TLSHandshakeError.missingExtension("key_share")
            }

            // Verify we have a key for this group
            guard let ourKeyExchange = state.context.keyExchange,
                  ourKeyExchange.group == serverKeyShare.serverShare.group else {
                throw TLSHandshakeError.noKeyShareMatch
            }

            // Perform key agreement
            let sharedSecret = try ourKeyExchange.sharedSecret(with: serverKeyShare.serverShare.keyExchangeData)
            state.context.sharedSecret = sharedSecret

            // Store cipher suite
            state.context.cipherSuite = serverHello.cipherSuite
            state.context.serverRandom = serverHello.randomData

            // Update transcript with ServerHello
            let serverHelloMessage = HandshakeCodec.encode(type: .serverHello, content: data)
            state.context.transcriptHash.update(with: serverHelloMessage)

            // Initialize or update key schedule for the selected cipher suite
            if !pskAccepted {
                // Non-PSK mode: reinitialize key schedule with no PSK
                state.context.keySchedule = TLSKeySchedule(cipherSuite: serverHello.cipherSuite)
                state.context.keySchedule.deriveEarlySecret(psk: nil)
            }
            // If PSK was accepted, early secret was already derived with PSK in startHandshake

            // Derive handshake secrets
            let transcriptHash = state.context.transcriptHash.currentHash()
            let (clientSecret, serverSecret) = try state.context.keySchedule.deriveHandshakeSecrets(
                sharedSecret: sharedSecret,
                transcriptHash: transcriptHash
            )

            state.context.clientHandshakeSecret = clientSecret
            state.context.serverHandshakeSecret = serverSecret

            // Hand the running transcript (CH..SH folded) + key schedule (at the
            // handshake-secret stage) to the Embedded-clean post-ServerHello auth FSM,
            // which now owns transcript folding, CertificateVerify/Finished
            // verification, and the application/exporter/resumption derivations.
            state.authMachine = QUICClientAuthMachine<QUICFoundationProvider>(
                transcript: state.context.transcriptHash.coreValue,
                keySchedule: state.context.keySchedule.coreValue,
                cipherSuite: serverHello.cipherSuite.coreCipherSuite,
                clientHandshakeSecret: clientSecret.bytes,
                serverHandshakeSecret: serverSecret.bytes,
                pskUsed: pskAccepted
            )

            // Transition state
            state.handshakeState = .waitEncryptedExtensions

            // Return keys available output
            return [
                .keysAvailable(KeysAvailableInfo(
                    level: .handshake,
                    clientSecret: clientSecret,
                    serverSecret: serverSecret
                ))
            ]
        }
    }

    // MARK: - Process HelloRetryRequest

    /// Process a HelloRetryRequest message
    /// - Parameters:
    ///   - hrr: The decoded HelloRetryRequest (ServerHello with special random)
    ///   - data: The raw message data
    ///   - state: The client state (mutable)
    /// - Returns: TLS outputs including the new ClientHello2
    private func processHelloRetryRequest(
        _ hrr: ServerHello,
        data: Data,
        state: inout ClientState
    ) throws -> [TLSOutput] {
        // Ensure we haven't already received an HRR (only one allowed)
        guard !state.context.receivedHelloRetryRequest else {
            throw TLSHandshakeError.unexpectedMessage("Received second HelloRetryRequest")
        }
        state.context.receivedHelloRetryRequest = true

        // Get the requested group from HRR
        guard let requestedGroup = hrr.helloRetryRequestSelectedGroup else {
            throw TLSHandshakeError.missingExtension("key_share in HelloRetryRequest")
        }

        // Verify we support the requested group
        let supportedGroups: [NamedGroup] = [.x25519, .secp256r1]
        guard supportedGroups.contains(requestedGroup) else {
            throw TLSHandshakeError.noKeyShareMatch
        }

        // Store cipher suite from HRR
        state.context.cipherSuite = hrr.cipherSuite

        // RFC 8446 Section 4.4.1: Special transcript handling for HRR
        // Save the hash of ClientHello1
        let clientHello1Hash = state.context.transcriptHash.currentHash()
        state.context.originalClientHello1Hash = clientHello1Hash

        // Replace transcript with message_hash synthetic message
        state.context.transcriptHash = TranscriptHash.fromMessageHash(
            clientHello1Hash: clientHello1Hash,
            cipherSuite: hrr.cipherSuite
        )

        // Add HRR to transcript
        let hrrMessage = HandshakeCodec.encode(type: .serverHello, content: data)
        state.context.transcriptHash.update(with: hrrMessage)

        // Generate new key pair for the requested group
        let newKeyExchange = try KeyExchange.generate(for: requestedGroup)
        state.context.keyExchange = newKeyExchange

        // Build ClientHello2 with the new key share
        let clientHello2 = try generateClientHello2(state: &state, keyExchange: newKeyExchange)

        // Transition state
        state.handshakeState = .waitServerHelloRetry

        // Return the new ClientHello
        return [.handshakeData(clientHello2, level: .initial)]
    }

    /// Generate ClientHello2 after HelloRetryRequest
    private func generateClientHello2(
        state: inout ClientState,
        keyExchange: KeyExchange
    ) throws -> Data {
        // Build extensions (similar to startHandshake but with new key_share)
        var extensions: [TLSExtension] = []

        // supported_versions (required for TLS 1.3)
        extensions.append(.supportedVersionsClient([TLSConstants.version13]))

        // supported_groups
        extensions.append(.supportedGroupsList([.x25519, .secp256r1]))

        // signature_algorithms - comprehensive list for wide compatibility
        extensions.append(.signatureAlgorithmsList([
            .ecdsa_secp256r1_sha256,
            .ecdsa_secp384r1_sha384,
            .rsa_pss_rsae_sha256,
            .rsa_pss_rsae_sha384,
            .rsa_pss_rsae_sha512,
            .ed25519
        ]))

        // key_share with the new key
        extensions.append(.keyShareClient([keyExchange.keyShareEntry()]))

        // ALPN
        if !state.configuration.alpnProtocols.isEmpty {
            extensions.append(.alpnProtocols(state.configuration.alpnProtocols))
        }

        // Server name (SNI)
        if let serverName = state.configuration.serverName {
            extensions.append(.serverName(ServerNameExtension(hostName: serverName)))
        }

        // QUIC transport parameters
        if let params = state.context.localTransportParameters {
            extensions.append(.quicTransportParameters(params))
        }

        // Build ClientHello2
        guard let clientRandom = state.context.clientRandom,
              let sessionID = state.context.sessionID else {
            throw TLSHandshakeError.internalError("Missing client random or session ID")
        }

        let clientHello = ClientHello(
            random: clientRandom,
            legacySessionID: sessionID,
            cipherSuites: [.tls_aes_128_gcm_sha256, .tls_aes_256_gcm_sha384],
            extensions: extensions
        )

        // Encode and update transcript
        let clientHelloMessage = clientHello.encodeAsHandshake()
        state.context.transcriptHash.update(with: clientHelloMessage)

        return clientHelloMessage
    }

    // MARK: - Process EncryptedExtensions

    /// Process an EncryptedExtensions message
    /// - Parameter data: The EncryptedExtensions message content
    /// - Returns: TLS outputs
    public func processEncryptedExtensions(_ data: Data) throws -> [TLSOutput] {
        return try state.withLock { state in
            guard state.handshakeState == .waitEncryptedExtensions else {
                throw TLSHandshakeError.unexpectedMessage("Unexpected EncryptedExtensions")
            }

            let encryptedExtensions = try EncryptedExtensions.decode(from: data)

            // Extract ALPN (required for QUIC per RFC 9001)
            guard let alpn = encryptedExtensions.selectedALPN else {
                throw TLSHandshakeError.noALPNMatch
            }
            // Verify server's ALPN is one we offered
            guard state.configuration.alpnProtocols.contains(alpn) else {
                throw TLSHandshakeError.noALPNMatch
            }
            state.context.negotiatedALPN = alpn

            // Extract QUIC transport parameters (required for QUIC)
            guard let params = encryptedExtensions.quicTransportParameters else {
                throw TLSHandshakeError.missingExtension("quic_transport_parameters")
            }
            state.context.peerTransportParameters = Data(params)

            // Check for early_data acceptance
            let earlyDataAccepted = encryptedExtensions.extensions.contains {
                $0.extensionType == .earlyData
            }

            if state.context.earlyDataState.attemptingEarlyData {
                state.context.earlyDataState.earlyDataAccepted = earlyDataAccepted
                // If early data was not accepted, client must discard any sent 0-RTT data
                // and retransmit in 1-RTT (handled at QUIC layer)
            }

            // Fold EncryptedExtensions + transition via the Embedded-clean auth FSM,
            // which now owns the transcript past ServerHello.
            guard var authMachine = state.authMachine else {
                throw TLSHandshakeError.internalError("Auth FSM not initialized")
            }
            let message = HandshakeCodec.encode(type: .encryptedExtensions, content: data)
            do {
                try authMachine.ingestEncryptedExtensions(rawMessageBytes: [UInt8](message))
            } catch let authError as TLSClientAuthError {
                throw TLSHandshakeError.from(authError)
            }
            state.authMachine = authMachine

            // Mirror the FSM's transition onto the adapter's observable state.
            state.handshakeState = authMachine.state.clientHandshakeState

            return []
        }
    }

    // MARK: - Process CertificateRequest

    /// Process a CertificateRequest message (for mutual TLS)
    ///
    /// RFC 8446 Section 4.3.2: Server requests client authentication.
    /// Client stores the context and will send Certificate + CertificateVerify after receiving Finished.
    /// - Parameter data: The CertificateRequest message content
    /// - Returns: TLS outputs
    public func processCertificateRequest(_ data: Data) throws -> [TLSOutput] {
        return try state.withLock { state in
            // CertificateRequest comes after EncryptedExtensions, before server's Certificate
            guard state.handshakeState == .waitCertificateOrCertificateRequest else {
                throw TLSHandshakeError.unexpectedMessage("Unexpected CertificateRequest in state \(state.handshakeState)")
            }

            let certRequest = try CertificateRequest.decode(from: data)

            // Store context to echo back in client's Certificate message
            state.context.certificateRequestContext = certRequest.certificateRequestContextData
            state.context.clientCertificateRequested = true

            // Fold CertificateRequest + transition via the auth FSM.
            guard var authMachine = state.authMachine else {
                throw TLSHandshakeError.internalError("Auth FSM not initialized")
            }
            let message = HandshakeCodec.encode(type: .certificateRequest, content: data)
            do {
                try authMachine.ingestCertificateRequest(rawMessageBytes: [UInt8](message))
            } catch let authError as TLSClientAuthError {
                throw TLSHandshakeError.from(authError)
            }
            state.authMachine = authMachine

            // Continue to wait for server's Certificate
            state.handshakeState = authMachine.state.clientHandshakeState

            return []
        }
    }

    // MARK: - Process Certificate

    /// Process a Certificate message
    /// - Parameter data: The Certificate message content
    /// - Returns: TLS outputs
    public func processCertificate(_ data: Data) throws -> [TLSOutput] {
        return try state.withLock { state in
            // Accept Certificate from either waiting state
            guard state.handshakeState == .waitCertificate ||
                  state.handshakeState == .waitCertificateOrCertificateRequest else {
                throw TLSHandshakeError.unexpectedMessage("Unexpected Certificate")
            }

            let certificate = try Certificate.decode(from: data)

            // Store raw certificates
            state.context.peerCertificates = certificate.certificatesData

            // X.509 path (skip if expectedPeerPublicKey is set — raw public key mode).
            if state.configuration.expectedPeerPublicKey == nil {
                guard let leafCertData = certificate.leafCertificateData else {
                    throw TLSHandshakeError.certificateVerificationFailed("No certificate provided")
                }

                // Parse the leaf certificate
                let leafCert: X509Certificate
                do {
                    leafCert = try X509Certificate.parse(from: leafCertData)
                } catch {
                    throw TLSHandshakeError.certificateVerificationFailed("Failed to parse certificate: \(error)")
                }

                // Store the parsed certificate
                state.context.peerCertificate = leafCert

                // Always extract and store the leaf public key. The CertificateVerify
                // proof-of-possession signature MUST be verified against it regardless
                // of `verifyPeer`: `verifyPeer` only controls X.509 chain/trust-anchor
                // validation, never the handshake signature. Otherwise a single flag
                // would yield an unauthenticated-but-"complete" channel (MITM).
                do {
                    state.context.peerVerificationKey = try leafCert.extractPublicKey()
                } catch {
                    throw TLSHandshakeError.certificateVerificationFailed("Failed to extract public key: \(error)")
                }

                // X.509 chain/trust-anchor validation is gated by verifyPeer.
                if state.configuration.verifyPeer {
                    // Parse intermediate certificates
                    let intermediateCerts = try certificate.certificatesData.dropFirst().compactMap { certData -> X509Certificate? in
                        try X509Certificate.parse(from: certData)
                    }

                    // Set up validation options
                    var validationOptions = X509ValidationOptions()
                    validationOptions.hostname = state.configuration.serverName
                    validationOptions.allowSelfSigned = state.configuration.allowSelfSigned
                    // RFC 5280 Section 4.2.1.12: Server certificates MUST have serverAuth EKU
                    validationOptions.requiredEKU = .serverAuth

                    // Create validator with trusted roots
                    let validator = X509Validator(
                        trustedRoots: state.configuration.trustedRootCertificates ?? [],
                        options: validationOptions
                    )

                    // Validate the certificate chain
                    do {
                        try validator.validate(certificate: leafCert, intermediates: Array(intermediateCerts))
                    } catch let error as X509Error {
                        throw TLSHandshakeError.certificateVerificationFailed(error.description)
                    }
                }
            }

            // Fold Certificate + transition via the auth FSM. The FSM records
            // whether a (non-empty) certificate was presented to drive the
            // fail-closed CertificateVerify branch.
            guard var authMachine = state.authMachine else {
                throw TLSHandshakeError.internalError("Auth FSM not initialized")
            }
            let message = HandshakeCodec.encode(type: .certificate, content: data)
            do {
                try authMachine.ingestServerCertificate(
                    certificatePresented: !certificate.isEmpty,
                    rawMessageBytes: [UInt8](message)
                )
            } catch let authError as TLSClientAuthError {
                throw TLSHandshakeError.from(authError)
            }
            state.authMachine = authMachine

            // Transition state
            state.handshakeState = authMachine.state.clientHandshakeState

            return []
        }
    }

    // MARK: - Process CertificateVerify

    /// Process a CertificateVerify message
    /// - Parameter data: The CertificateVerify message content
    /// - Returns: TLS outputs
    public func processCertificateVerify(_ data: Data) throws -> [TLSOutput] {
        return try state.withLock { state in
            guard state.handshakeState == .waitCertificateVerify else {
                throw TLSHandshakeError.unexpectedMessage("Unexpected CertificateVerify")
            }

            let certificateVerify = try CertificateVerify.decode(from: data)

            // Resolve the peer public-key bytes (X.509 stays adapter-side): either the
            // explicitly configured key, or the one extracted from the certificate.
            // The CertificateVerify proof-of-possession signature is then verified
            // inside the Embedded-clean auth FSM, fail-closed and independent of
            // `verifyPeer`.
            let peerPublicKey: QUICClientAuthMachine<QUICFoundationProvider>.PeerPublicKey?
            if let expectedPublicKey = state.configuration.expectedPeerPublicKey {
                // The configured raw public key must be importable under the
                // CertificateVerify algorithm; surface a scheme mismatch loudly.
                let verificationKey = try VerificationKey(
                    publicKeyBytes: expectedPublicKey,
                    scheme: certificateVerify.algorithm
                )
                peerPublicKey = .init(
                    bytes: [UInt8](verificationKey.publicKeyBytes),
                    scheme: verificationKey.scheme
                )
            } else if let extractedKey = state.context.peerVerificationKey {
                peerPublicKey = .init(
                    bytes: [UInt8](extractedKey.publicKeyBytes),
                    scheme: extractedKey.scheme
                )
            } else {
                peerPublicKey = nil
            }

            // Verify (fail-closed) + fold via the auth FSM. The FSM holds the live
            // transcript (CH..Certificate), so the signed content is byte-identical.
            guard var authMachine = state.authMachine else {
                throw TLSHandshakeError.internalError("Auth FSM not initialized")
            }
            let message = HandshakeCodec.encode(type: .certificateVerify, content: data)
            do {
                try authMachine.ingestServerCertificateVerify(
                    algorithm: certificateVerify.algorithm,
                    signature: certificateVerify.signature,
                    peerPublicKey: peerPublicKey,
                    verifyPeer: state.configuration.verifyPeer,
                    rawMessageBytes: [UInt8](message)
                )
            } catch let authError as TLSClientAuthError {
                throw TLSHandshakeError.from(authError)
            }
            state.authMachine = authMachine

            // Call custom certificate validator if configured
            // This is where libp2p validates the libp2p extension and extracts PeerID
            if let validator = state.configuration.certificateValidator,
               let peerCerts = state.context.peerCertificates {
                let peerInfo = try validator(peerCerts)
                state.context.validatedPeerInfo = peerInfo
            }

            // Transition state
            state.handshakeState = authMachine.state.clientHandshakeState

            return []
        }
    }

    // MARK: - Process Finished

    /// Process a server Finished message
    /// - Parameter data: The Finished message content
    /// - Returns: TLS outputs including application keys and client Finished
    public func processServerFinished(_ data: Data) throws -> (outputs: [TLSOutput], clientFinished: Data) {
        return try state.withLock { state in
            // Finished is accepted ONLY in .waitFinished. A full (certificate-based)
            // handshake reaches .waitFinished only after Certificate + CertificateVerify
            // have been processed; a PSK/resumption handshake transitions directly to
            // .waitFinished after EncryptedExtensions (Certificate legitimately omitted).
            // Accepting Finished in .waitCertificate/.waitCertificateVerify would let a
            // server skip authentication entirely (unauthenticated/MITM) — forbidden.
            guard state.handshakeState == .waitFinished else {
                throw TLSHandshakeError.unexpectedMessage("Unexpected Finished in state \(state.handshakeState)")
            }

            let serverFinished = try Finished.decode(from: data)

            guard var authMachine = state.authMachine else {
                throw TLSHandshakeError.internalError("Auth FSM not initialized")
            }

            // Verify the server Finished MAC (constant-time), fold it, and derive the
            // application + exporter secrets — all inside the Embedded-clean auth FSM.
            let postFinished: QUICClientAuthMachine<QUICFoundationProvider>.PostFinishedSecrets
            do {
                postFinished = try authMachine.ingestServerFinished(
                    verifyData: serverFinished.verifyData)
            } catch let authError as TLSClientAuthError {
                throw TLSHandshakeError.from(authError)
            }

            let clientAppSecret = SymmetricKey(data: postFinished.clientApplicationSecret)
            let serverAppSecret = SymmetricKey(data: postFinished.serverApplicationSecret)
            state.context.clientApplicationSecret = clientAppSecret
            state.context.serverApplicationSecret = serverAppSecret
            state.context.exporterMasterSecret = SymmetricKey(data: postFinished.exporterMasterSecret)

            // === Client Certificate and CertificateVerify (for mutual TLS) ===
            // RFC 8446 Section 4.4: If server sent CertificateRequest, client responds
            // with Certificate and CertificateVerify BEFORE Finished. The adapter
            // builds + signs these (X.509 / signing-key stays adapter-side); the FSM
            // folds the bytes so the transcript stays correct.
            var clientCertMessages: [Data] = []

            if state.context.clientCertificateRequested {
                // Check if client has certificate material configured
                if let signingKey = state.configuration.signingKey,
                   let certChain = state.configuration.certificateChain,
                   !certChain.isEmpty {

                    // Send Certificate (with echoed context from CertificateRequest)
                    let certificate = Certificate(
                        certificateRequestContext: state.context.certificateRequestContext,
                        certificates: certChain
                    )
                    let certMessage = certificate.encodeAsHandshake()
                    do {
                        try authMachine.foldClientCertificate(rawMessageBytes: [UInt8](certMessage))
                    } catch let authError as TLSClientAuthError {
                        throw TLSHandshakeError.from(authError)
                    }
                    clientCertMessages.append(certMessage)

                    // Send CertificateVerify — sign the transcript (CH..client-Cert)
                    // the FSM exposes (signing-key path is adapter-side).
                    let signatureContent = TLSSignature.certificateVerifyContent(
                        transcriptHash: Data(authMachine.clientCertificateVerifyTranscript),
                        isServer: false  // This is CLIENT's CertificateVerify
                    )

                    let signature = try signingKey.sign(signatureContent)
                    let certificateVerify = CertificateVerify(
                        algorithm: signingKey.scheme,
                        signature: signature
                    )
                    let cvMessage = certificateVerify.encodeAsHandshake()
                    do {
                        try authMachine.foldClientCertificateVerify(rawMessageBytes: [UInt8](cvMessage))
                    } catch let authError as TLSClientAuthError {
                        throw TLSHandshakeError.from(authError)
                    }
                    clientCertMessages.append(cvMessage)
                } else {
                    // Client has no certificate material - send empty Certificate
                    // RFC 8446 Section 4.4.2: If client has no certificates, send empty list
                    let emptyCertificate = Certificate(
                        certificateRequestContext: state.context.certificateRequestContext,
                        certificates: []
                    )
                    let certMessage = emptyCertificate.encodeAsHandshake()
                    do {
                        try authMachine.foldClientCertificate(rawMessageBytes: [UInt8](certMessage))
                    } catch let authError as TLSClientAuthError {
                        throw TLSHandshakeError.from(authError)
                    }
                    clientCertMessages.append(certMessage)
                    // No CertificateVerify for empty certificate
                }
            }

            // Generate client Finished + derive the resumption master secret inside
            // the FSM, which transitions to `.connected`.
            let clientFinishedMessage: Data
            do {
                clientFinishedMessage = Data(try authMachine.produceClientFinished())
            } catch let authError as TLSClientAuthError {
                throw TLSHandshakeError.from(authError)
            }
            if let resumption = authMachine.resumptionMasterSecret {
                state.context.resumptionMasterSecret = SymmetricKey(data: resumption)
            }

            // Combine all client messages: [Certificate, CertificateVerify], Finished
            let allClientMessages = clientCertMessages + [clientFinishedMessage]
            let combinedClientMessage = allClientMessages.reduce(Data()) { $0 + $1 }

            // Sync the FSM's transcript + key schedule back onto the context so the
            // post-handshake paths (NewSessionTicket / key update) observe the
            // completed state.
            state.context.transcriptHash.coreValue = authMachine.currentTranscript
            state.context.keySchedule.coreValue = authMachine.currentKeySchedule
            state.authMachine = authMachine

            // Transition state
            state.handshakeState = authMachine.state.clientHandshakeState

            var outputs: [TLSOutput] = []

            // Application keys
            outputs.append(.keysAvailable(KeysAvailableInfo(
                level: .application,
                clientSecret: clientAppSecret,
                serverSecret: serverAppSecret
            )))

            // Handshake complete
            outputs.append(.handshakeComplete(HandshakeCompleteInfo(
                alpn: state.context.negotiatedALPN,
                zeroRTTAccepted: state.context.earlyDataState.earlyDataAccepted,
                resumptionTicket: nil
            )))

            // Return combined message (Certificate + CertificateVerify + Finished for mTLS,
            // or just Finished for non-mTLS)
            return (outputs, combinedClientMessage)
        }
    }

    // MARK: - Process NewSessionTicket

    /// Process a NewSessionTicket message (received post-handshake)
    /// - Parameter data: The NewSessionTicket message content
    /// - Returns: The derived session ticket data for future use
    public func processNewSessionTicket(_ data: Data) throws -> SessionTicketData {
        return try state.withLock { state in
            guard state.handshakeState == .connected else {
                throw TLSHandshakeError.unexpectedMessage("NewSessionTicket received before handshake complete")
            }

            let ticket = try NewSessionTicket.decode(from: data)

            // Get resumption master secret
            guard let resumptionMasterSecret = state.context.resumptionMasterSecret,
                  let cipherSuite = state.context.cipherSuite else {
                throw TLSHandshakeError.internalError("Missing resumption master secret or cipher suite")
            }

            // Derive PSK from resumption master secret and ticket nonce
            let resumptionPSK = state.context.keySchedule.deriveResumptionPSK(
                resumptionMasterSecret: resumptionMasterSecret,
                ticketNonce: ticket.ticketNonceData
            )

            // Extract max early data size from extensions
            var maxEarlyDataSize: UInt32 = 0
            for ext in ticket.extensions {
                if case .earlyData(let earlyData) = ext {
                    if case .newSessionTicket(let size) = earlyData {
                        maxEarlyDataSize = size
                    }
                }
            }

            // Create session ticket data
            let ticketData = SessionTicketData(
                ticket: ticket.ticketData,
                resumptionPSK: resumptionPSK.withUnsafeBytes { Data($0) },
                maxEarlyDataSize: maxEarlyDataSize,
                ticketAgeAdd: ticket.ticketAgeAdd,
                receiveTime: Date(),
                lifetime: ticket.ticketLifetime,
                cipherSuite: cipherSuite,
                serverName: state.configuration.serverName,
                alpn: state.context.negotiatedALPN
            )

            return ticketData
        }
    }

    // MARK: - Accessors

    /// Current handshake state
    public var handshakeState: ClientHandshakeState {
        state.withLock { $0.handshakeState }
    }

    /// Whether the handshake is complete
    public var isConnected: Bool {
        state.withLock { $0.handshakeState == .connected }
    }

    /// Negotiated ALPN protocol
    public var negotiatedALPN: String? {
        state.withLock { $0.context.negotiatedALPN }
    }

    /// Peer transport parameters
    public var peerTransportParameters: Data? {
        state.withLock { $0.context.peerTransportParameters }
    }

    /// Exporter master secret (available after handshake completion)
    public var exporterMasterSecret: SymmetricKey? {
        state.withLock { $0.context.exporterMasterSecret }
    }

    /// Whether PSK was used in this handshake
    public var pskUsed: Bool {
        state.withLock { $0.context.pskUsed }
    }

    /// Whether early data (0-RTT) was accepted by the server
    public var earlyDataAccepted: Bool {
        state.withLock { $0.context.earlyDataState.earlyDataAccepted }
    }

    /// Resumption master secret (for deriving new session tickets)
    public var resumptionMasterSecret: SymmetricKey? {
        state.withLock { $0.context.resumptionMasterSecret }
    }

    /// Peer certificates (raw DER data, leaf certificate first)
    public var peerCertificates: [Data]? {
        state.withLock { $0.context.peerCertificates }
    }

    /// Parsed peer leaf certificate
    public var peerCertificate: X509Certificate? {
        state.withLock { $0.context.peerCertificate }
    }

    /// Validated peer info from certificate validator callback.
    ///
    /// This contains the value returned by `TLSConfiguration.certificateValidator`
    /// after successful certificate validation (e.g., PeerID for libp2p).
    public var validatedPeerInfo: (any Sendable)? {
        state.withLock { $0.context.validatedPeerInfo }
    }
}

// MARK: - SymmetricKey bytes helper

extension SymmetricKey {
    /// The raw key bytes (host-only bridge for the `[UInt8]`-based auth FSM core).
    fileprivate var bytes: [UInt8] {
        withUnsafeBytes { [UInt8]($0) }
    }
}

// MARK: - Auth FSM state ↔ adapter state bridge

extension QUICClientAuthMachine<QUICFoundationProvider>.AuthState {
    /// The adapter's observable `ClientHandshakeState` mirroring this FSM state, so
    /// existing accessors and tests see identical states.
    var clientHandshakeState: ClientHandshakeState {
        switch self {
        case .waitEncryptedExtensions: return .waitEncryptedExtensions
        case .waitCertificateOrCertificateRequest: return .waitCertificateOrCertificateRequest
        case .waitCertificate: return .waitCertificate
        case .waitCertificateVerify: return .waitCertificateVerify
        case .waitFinished: return .waitFinished
        case .connected: return .connected
        }
    }
}

// MARK: - TLSClientAuthError → TLSHandshakeError bridge

extension TLSHandshakeError {
    /// Maps an Embedded-clean ``TLSClientAuthError`` from the auth FSM core onto the
    /// adapter's `TLSHandshakeError` so existing error-handling / alert mapping and
    /// the auth tests observe identical behaviour.
    static func from(_ error: TLSClientAuthError) -> TLSHandshakeError {
        switch error {
        case .unexpectedMessage(let tag):
            return .unexpectedMessage("Unexpected message in state \(tag)")
        case .noALPNMatch:
            return .noALPNMatch
        case .missingExtension:
            return .missingExtension("quic_transport_parameters")
        case .invalidExtension:
            return .invalidExtension("invalid handshake extension")
        case .signatureVerificationFailed:
            return .signatureVerificationFailed
        case .certificateVerificationFailed:
            return .certificateVerificationFailed("No public key available to verify CertificateVerify")
        case .finishedVerificationFailed:
            return .finishedVerificationFailed
        case .missingSecret:
            return .internalError("Missing handshake secret")
        case .wire(let wireError):
            return .decodeError("\(wireError)")
        case .keySchedule(let scheduleError):
            return .internalError("Key schedule error: \(scheduleError)")
        case .signature:
            return .signatureVerificationFailed
        }
    }
}
